"use client"

import { Button } from "@/ui/primitives/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/ui/feedback/card"
import { Field, FieldDescription } from "@/ui/primitives/field"
import { Input } from "@/ui/primitives/input"
import { Label } from "@/ui/primitives/label"
import { useState, useEffect } from "react"
import { createReviewAction } from "@/app/actions/reviews"
import { useAuth } from "@/features/auth/hooks/useAuth"
import { useRouter, useSearchParams } from "next/navigation"
import Link from "next/link"

export default function ReviewRegisterPage() {
  const { currentUser, loading } = useAuth()
  const router = useRouter()
  const searchParams = useSearchParams()
  const propertyId = searchParams.get("propertyId")
  const address = searchParams.get("address") || ""
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState("")


  //following function generated by Claude Sonnet 4.5

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    
    if (!currentUser) {
      setError("Du må være logget inn for å legge til en anmeldelse")
      return
    }

    if (!propertyId) {
      setError("Fant ikke bolig-ID")
      return
    }
    
    setIsSubmitting(true)
    setError("")
    
    const formData = new FormData(e.currentTarget)
    formData.append("propertyId", propertyId)
    formData.append("userId", currentUser.uid)
    
    try {
      const result = await createReviewAction(formData)
      
      if ("error" in result) {
        setError(result.error)
        setIsSubmitting(false)
        return
      }
      
      alert("Anmeldelse lagt til!")
      router.back()
    } catch (err) {
      setError("Noe gikk galt")
    } finally {
      setIsSubmitting(false)
    }
  }

// end of generated function


  if (loading) {
    return (
      <main className="bg-muted min-h-screen flex items-center justify-center p-6">
        <div className="text-center">Laster...</div>
      </main>
    )
  }

  if (!currentUser) {
    return null
  }

  return (
    <main className="bg-muted min-h-screen flex items-center justify-center p-6">
      <div className="flex w-full max-w-lg flex-col items-center gap-6">
        <Link href="/" className="font-bold text-4xl text-blue-700">
          Utleiometer
        </Link>

        <Card className="w-full">
          <CardHeader>
            <CardTitle className="text-xl">Legg til anmeldelse for {address}</CardTitle>
            <CardDescription>
              Del din erfaring med denne boligen
            </CardDescription>
          </CardHeader>

          <CardContent>
            <form
              className="flex flex-col gap-6"
              onSubmit={handleSubmit}
            >
              <div className="space-y-4">

                <div className="grid gap-2">
                  <Label htmlFor="comment">
                    Beskriv boligen
                  </Label>
                  <textarea
                    id="comment"
                    name="comment"
                    placeholder="F.eks. Stille nabolag, litt langt fra sentrum"
                    className="min-h-[100px] rounded-md border bg-background px-3 py-2 text-sm"
                    required
                  />
                </div>

                <div className="grid gap-2">
                  <Label htmlFor="rating">
                    Vurdering (1–5)
                  </Label>
                  <Input
                    id="rating"
                    name="rating"
                    type="number"
                    min={1}
                    max={5}
                    step={1}
                    placeholder="3"
                    required
                  />
                </div>
              </div>

              {error && (
                <div className="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-800">
                  {error}
                </div>
              )}

              <Button type="submit" className="w-full" disabled={isSubmitting}>
                {isSubmitting ? "Legger til..." : "Legg til anmeldelse"}
              </Button>

              <Field>
                <FieldDescription className="text-center">
                  Du kan redigere anmeldelsen senere
                </FieldDescription>
              </Field>
            </form>
          </CardContent>

          <CardFooter />
        </Card>
      </div>
    </main>
  )
}
