import { adminDb } from "./admin";

export interface Property {
  propertyId: string;
  address: string;
  zipCode: string;
  city: string;
  registeredByUid: string;
  createdAt: Date;
  imageUrl?: string;
}

export async function createProperty(data: Omit<Property, "propertyId" | "createdAt">) {
    const propertyData = { ...data, createdAt: new Date() };
    const docRef = await adminDb.collection("properties").add(propertyData);
    return { propertyId: docRef.id, ...propertyData };
}

export async function getPropertyById(propertyId: string) {
    const doc = await adminDb.collection("properties").doc(propertyId).get();
    if (!doc.exists) {
        throw new Error("Property not found");
    }
    return { propertyId: doc.id, ...doc.data() } as Property;
}

export async function getAllProperties() {
    const snapshot = await adminDb.collection("properties").get();
    return snapshot.docs.map(doc => ({ propertyId: doc.id, ...doc.data() } as Property));
}

// generated by Claude Sonnet 4
export async function getPropertyByAddress(address: string, zipCode: string, city: string) {
  const snapshot = await adminDb
    .collection("properties")
    .where("address", "==", address)
    .where("zipCode", "==", zipCode)
    .where("city", "==", city)
    .get();
  
  if (snapshot.empty) {
    return null;
  }
  
  const doc = snapshot.docs[0];
  return { propertyId: doc.id, ...doc.data() } as Property;
}