export const env = {
// Client-side (synlige i browser - NEXT_PUBLIC prefix)
NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY!,
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN!,
NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID!,

// Server-side only (admin SDK)
FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID!,
FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL!,
FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY!,
}
