"use client"

import { Button } from "@/ui/primitives/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/ui/feedback/card"
import { Field, FieldDescription } from "@/ui/primitives/field"
import { Input } from "@/ui/primitives/input"
import { Label } from "@/ui/primitives/label"
import { useState, useEffect } from "react"
import { createReviewAction } from "@/app/actions/reviews"
import { createPropertyAction } from "@/app/actions/properties"
import { useAuth } from "@/features/auth/hooks/useAuth"
import { useRouter } from "next/navigation"

import Link from "next/link"

export default function PropertyRegisterPage() {
  const { currentUser, loading } = useAuth()
  const router = useRouter()
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState("")

  // Generated by Claude Sonnet 4.5: 
  // PROTECTION: Redirect to login if not authenticated
  useEffect(() => {
    if (!loading && !currentUser) {
      router.push("/login")
    }
  }, [currentUser, loading, router])


  //following function generated by Claude Sonnet 4.5

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
  e.preventDefault()
  
  if (!currentUser) {
    setError("You must be logged in to register a property")
    return
  }
  
  setIsSubmitting(true)
  setError("")
  
  const formData = new FormData(e.currentTarget)
  
  try {
 
    const propertyResult = await createPropertyAction(formData)
    
    if ("error" in propertyResult) {
      setError(propertyResult.error)
      setIsSubmitting(false)
      return
    }
    
    formData.append("propertyId", propertyResult.propertyId)
    formData.append("userId", currentUser.uid)
    
    await createReviewAction(formData)
    
    alert("Success! Property and review created")
  } catch (err) {
    setError("Something went wrong")
  } finally {
    setIsSubmitting(false)
  }
}

// end of generated function


  if (loading) {
    return (
      <main className="bg-muted min-h-screen flex items-center justify-center p-6">
        <div className="text-center">Laster...</div>
      </main>
    )
  }

  if (!currentUser) {
    return null
  }

  return (
    <main className="bg-muted min-h-screen flex items-center justify-center p-6">
      <div className="flex w-full max-w-lg flex-col items-center gap-6">
        <Link href="/" className="font-bold text-4xl text-blue-700">
          Utleiometer
        </Link>

        <Card className="w-full">
          <CardHeader>
            <CardTitle className="text-xl">Registrer og anmeld bolig</CardTitle>
            <CardDescription>
              Registrer adressen og del din erfaring
            </CardDescription>
          </CardHeader>

          <CardContent>
            <form
              className="flex flex-col gap-8"
              onSubmit={handleSubmit}
            >

              {/* === 1. REGISTRER BOLIG === */}
              <div className="space-y-4">
                <h3 className="text-base font-semibold">
                  📍 Registrer bolig
                </h3>

                <div className="grid gap-2">
                  <Label htmlFor="address">Adresse</Label>
                  <Input
                    id="address"
                    name="address"
                    type="text"
                    placeholder="F.eks. Elgeseter gate 1"
                    required
                  />
                </div>

                <div className="grid gap-2">
                  <Label htmlFor="zipCode">Postnummer</Label>
                  <Input
                    id="zipCode"
                    name="zipCode"
                    type="text"
                    placeholder="7030"
                    required
                  />
                </div>

                <div className="grid gap-2">
                  <Label htmlFor="city">By</Label>
                  <Input
                    id="city"
                    name="city"
                    type="text"
                    placeholder="Trondheim"
                    required
                  />
                </div>
              </div>

              <div className="border-t" />

              {/* === 2. ANMELDELSE AV BOLIG === */}
              <div className="space-y-4">
                <h3 className="text-base font-semibold">
                  🏠 Anmeld bolig
                </h3>

                <div className="grid gap-2">
                  <Label htmlFor="comment">
                    Beskriv boligen
                  </Label>
                  <textarea
                    id="comment"
                    name="comment"
                    placeholder="F.eks. Stille nabolag, litt langt fra sentrum"
                    className="min-h-[100px] rounded-md border bg-background px-3 py-2 text-sm"
                    required
                  />
                </div>

                <div className="grid gap-2">
                  <Label htmlFor="rating">
                    Vurdering (1–5)
                  </Label>
                  <Input
                    id="rating"
                    name="rating"
                    type="number"
                    min={1}
                    max={5}
                    step={1}
                    placeholder="3"
                    required
                  />
                </div>
              </div>

              <Button type="submit" className="w-full">
                Registrer bolig
              </Button>

              <Field>
                <FieldDescription className="text-center">
                  Du kan redigere anmeldelsen senere
                </FieldDescription>
              </Field>
            </form>
          </CardContent>

          <CardFooter />
        </Card>
      </div>
    </main>
  )
}
